apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-hub
spec:
  selector:
    matchLabels:
      app: image-hub
  replicas: 2
  template:
    metadata:
      labels:
        app: image-hub
    spec:
      containers:
        - name: ih-container
          image: brycehamilton/image-hub
          ports:
            - containerPort: 3000
